# Generated by Django 3.2.8 on 2024-10-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='psswd',
            field=models.CharField(default='SGARxn09lE1UesIT3mYa', max_length=20, unique=True),
        ),
    ]
